### ISSUE TITLE
replace "constant" with "pure"/"view" in functions

### ISSUE THREAD

**Issue by pauliax** [realitio/realitio-dapp#101]
from 18 compiler version (if I remember correctly) "constant" is deprecated in the function definition. Use "pure" / "view" instead. For instance, here:

```
   function getDisputeFee(bytes32 question_id) 
    public constant returns (uint256) {...}
```

**Comment by edmundedgar** [comment]
Yes, this was deprecated after we froze and sent it to the auditor. More recent solc will also nag us about renaming "Log" events "Emit". We'll only update this if we need to make a other serious changes that would justify going through the whole process again.

**Comment by edmundedgar** [comment]
Replaced by https://github.com/realitio/realitio-contracts/issues/7
