### ISSUE TITLE
Entering a custom arbitrator always fails validateArbitratorForContract

### ISSUE THREAD

**Issue by satello** [realitio/realitio-dapp#173]
See https://github.com/realitio/realitio-dapp/blob/10e322bd653d523e22d8f40068f94f82dfe2f880/js/ui/main.js#L4245

The contract call is fetching the Realitio contract address and then compares it against the Arbitrator address which will always fail. Should compare `realitio_addr == rslt`

**Comment by edmundedgar** [comment]
@satello Nice catch, fixed
